name:                duplicates
version:             0.1.0.0
github:              "githubuser/duplicates"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/duplicates#readme>

dependencies:
- base >= 4.7 && < 5
- tokenize
- text
- Unique
- rio

executables:
  duplicates:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    when:
    - condition: flag(static)
      ld-options:
      - -static
      - -pthread

flags:
  static:
    description: Pass -static/-pthread to ghc when linking the stack binary.
    manual: true
    default: false

